### ISSUE TITLE
resize callback not called on safari

### ISSUE THREAD

**Issue by daviduhlir** [Justineo/resize-detector#11]
Hello, on safari (tested on 13.0.4 (14608.4.9.1.4)) resize callback is never called. Same application is working in chrome, and callback was called correctly. Thank you.

**Comment by Justineo** [comment]
https://justineo.github.io/resize-detector/demo/

This demo is working on Safari 13.0.4 according to my tests. Can you provide a minimal reproduction of your problem?

**Comment by daviduhlir** [comment]
Thank you, for that fast response, your example is working. I think problem may be that I'm trying to detect resize on image. I forgot to says I'm using it in combination of rect, so I hope, my think is correct.

Here is my example code:

```import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { addListener as resizeAddListener } from 'resize-detector';

class Component extends React.Component {
    public render() {
        return (
            <img src="some image url" ref={this.onRef} />
        );
    }

    protected onRef = (e) => {
        if (e) {
            console.log(e);
            resizeAddListener(e, () => console.log("resized!"));
        }
    }
}

ReactDOM.render(<Component />, document.getElementById('root'));
```

**Comment by Justineo** [comment]
Oh, this is a known issue. For browsers that don't support `ResizeObserver` yet, `resize-detector` will fall back to a scroll-based size detection mechanism. To use this approach, several dummy elements will be inserted to the target element so it cannot be an `<img>`. You can work this around by putting a wrapper element outside the `<img>` element.

You can also try [resize-observer-polyfill](https://github.com/que-etc/resize-observer-polyfill) instead of this package. The differences are already discussed in our [README](https://github.com/Justineo/resize-detector#limitations-and-caveats) section and you can decide which one fits your purpose the best.

**Comment by daviduhlir** [comment]
Sorry and thank you very much, I didn't know about that.
